### ISSUE TITLE
World crash upon exploring with pfaa

### ISSUE THREAD

**Issue by 31trainman** [lawremi/PerFabricaAdAstra#56] opened 2016-05-12 15:01 UTC
Upon the creation of a new world with pfaa it takes along time to load and upon joining and exploring for a few chunks it crashes

Heres the error report http://pastebin.com/2hERabYQ

Mod list
http://pastebin.com/RrrNfhL8

Forge 1614
Minecraft 1.7.10
Mac os x 10.11.4
Java 8 update 91

**Comment by lawremi** [comment] 2016-05-13 02:18
Please remove mods until the error goes away, perhaps starting with Reika's mods and fastcraft, but it's probably something else.

**Comment by 31trainman** [comment] 2016-05-13 12:12
It's dragon API and something about block composition

**Comment by lawremi** [comment] 2016-05-13 14:10
Could you please elaborate? How did you get the idea that it is "something about block composition"?

**Comment by 31trainman** [comment] 2016-05-13 14:21
From the crash report I see dragon API mentioned and block composition but I can't tell what's causing the crash

**Comment by lawremi** [comment] 2016-05-13 20:03
Did you actually try removing DragonAPI (and its dependencies) to see if the problem goes away? Stack traces can be misleading.

**Comment by 31trainman** [comment] 2016-05-13 21:05
il copy my modpack test and try

**Comment by 31trainman** [comment] 2016-05-13 22:10
The crash doesn't happen when dragonapi etc isn't present

**Comment by lawremi** [comment] 2016-05-14 03:11
Maybe @ReikaKalseki could lend a hand here. Somehow one of the Geologica blocks is being rendered with the wrong meta, though it's not clear how DragonAPI would be at fault.

**Comment by ReikaKalseki** [comment] 2016-05-14 03:52
That stacktrace contains no reference to any of my code, and aside from a RenderBlockEvent (ASMed into WorldRenderer) no interaction with the WorldRenderer.

**Comment by lawremi** [comment] 2016-05-14 03:56
Well according to 31trainman, removing DragonAPI and its dependencies avoids the error... so there is some sort of interaction.

**Comment by ReikaKalseki** [comment] 2016-05-14 05:32
With no indications as to a source, I can neither explain nor offer a solution.

**Comment by lawremi** [comment] 2016-05-14 17:57
@31trainman would you please try to establish a minimal set of mods for reproducing the issue?

**Comment by 31trainman** [comment] 2016-05-14 21:16
ok, Do you have discord or something @lawremi for making it easier to fix problems like this?

**Comment by 31trainman** [comment] 2016-05-17 01:21
iv created a test of pfaa custom ore gen and dragon api, rotary craft and reactor craft and am seeing massive lag.

**Comment by ReikaKalseki** [comment] 2016-05-17 03:22
Not even remotely related.

**Comment by 31trainman** [comment] 2016-05-17 13:19
Strange then as testing with only those mods hasn't resulted in a crash only lag and that error coming up

**Comment by lawremi** [comment] 2016-05-17 13:28
There is some other mod causing the problem. Btw, chunk gen lag can be reduced with fastcraft.

**Comment by recalcitrantQ** [comment] 2016-05-21 16:12
I have also encountered this crash. 

My crash report is http://pastebin.com/9gT3y4Gk
and my modlist is http://pastebin.com/ZRj1eKuG

**Comment by ReikaKalseki** [comment] 2016-05-21 19:11
And that demonstrates not needing DragonAPI.

**Comment by 31trainman** [comment] 2016-05-21 19:36
@ReikaKalseki It looks to be something with pfaa and one of your mods ores using pfaa's block composition thing

**Comment by ReikaKalseki** [comment] 2016-05-22 00:31
Do you even read what gets posted? recalcitrant does not even have DragonAPI installed. Unless you want to argue that DragonAPI is so bad that it breaks things even without being present, this has been demonstrated to be outside my doing.

**Comment by 31trainman** [comment] 2016-05-22 01:14
Yes I do @reika it's on geologica's side some interaction with dragonapi

**Comment by lawremi** [comment] 2016-05-22 01:47
@31trainman please come up with a minimal list of mods that reproduces one of these crashes. There are semi-popular modpacks that combine Reika's mods with PFAA, without any known issue, so it's probably an interaction with one of the lesser known mods on your list.

**Comment by recalcitrantQ** [comment] 2016-05-22 02:06
Crash reproduced with modlist of 

fastcraft-1.23.jar
gases-1.7.10-1.6.3.jar
gasesFramework-1.7.10-1.2.0.jar
PFAA-1.7.10-0.2.27.jar
CustomOreGen-1.7.10-1.2.21.jar

**Comment by ReikaKalseki** [comment] 2016-05-22 03:04
> Yes I do @reika it's on geologica's side some interaction with dragonapi

OK, in that case you are just stupid, because you are arguing that a mod can crash without even being installed, and have insisted that you have understood the idiocy of what you are saying. Stop wasting people's time and learn either how to read or how to use basic reasoning.

**Comment by recalcitrantQ** [comment] 2016-05-22 03:27
The crash is related to block metadata. Geologica is expecting metadata value to be within a certain range, but it is beyond that range due to being set by another mod. That's my current understanding at least

**Comment by ReikaKalseki** [comment] 2016-05-22 04:18
I have had people report similar issues with ElectriCraft, ReactorCraft, and ChromatiCraft ores. A year in, there is still no consensus or consistent cause.

**Comment by lawremi** [comment] 2016-05-22 14:04
@31trainman would you please contact the maintainer of Glenn's Gases to see if he might have any clue.

**Comment by 31trainman** [comment] 2016-05-22 18:36
Sure @lawremi, perhaps pfaa is interacting with the gases from Glenn's gasses and somehow dragonapi is seeing this and trying to render fire and then fastcraft is somehow interacting with the rendering of said fire.

**Comment by ReikaKalseki** [comment] 2016-05-22 19:10
> perhaps pfaa is interacting with the gases from Glenn's gasses and somehow dragonapi is seeing this and trying to render fire and then fastcraft is somehow interacting with the rendering of said fire

The only thing in that even approximating accuracy is the possibility of the gases being involved, as they may be setting the metadatas of adjacent blocks as they flow.

> dragonapi is seeing this and trying to render fire

And there you go accusing a mod of breaking things without being installed, this time also adding a bonus of thoroughly demonstrating that you lack an understanding of not only basic logic but of the code as well.

**Comment by 31trainman** [comment] 2016-05-22 19:24
I have a fresh crash and clearly see DragonApi involved as I have it installed
http://pastebin.com/BS271Kim

Mod list http://pastebin.com/FqxDFA4q

**Comment by recalcitrantQ** [comment] 2016-05-22 19:34
DragonAPI being in the stacktrace doesn't mean it has anything to do with the crash, any more than fastcraft does. 

What this looks like to me is incompatibility between Iocalfaeus Gas and Geologica. Iocalfaeus Gas increases the metadata value of adjacent stone blocks to track how much it's heated up, which would throw off Geologica's rendering when it tries to determine the GeoMaterial

**Comment by JamiesWhiteShirt** [comment] 2016-05-22 19:44
Glenn's Gases dev here.

I'm fairly certain DragonAPI is not involved even though it appears in the stack trace, it's merely injected itself into block rendering but acts normally in most cases (https://github.com/ReikaKalseki/DragonAPI/blob/master/Instantiable/Event/Client/RenderBlockAtPosEvent.java#L51). There's still no reason to be an ass about it.

@recalcitrantQ is partially correct. Iocalfaeus gas uses metadata to track block temperature, but it's using it's own block ("gases:warmStone"). This block does inherit BlockStone. Could this perhaps make PerFabricaAdAstra assume it is a static type of stone? By the way, this mechanic is currently being reworked, so the issue might resolve itself soon.

While it doesn't resolve the issue, I found it useful to avoid fast-failing during rendering as it causes more problems than debugging material, so it might be useful to add a bounds check.

**Comment by flyingbanana** [comment] 2016-05-22 20:06
Actually, DragonAPI being in the stacktrace means it's reika's fault. Case closed.

**Comment by recalcitrantQ** [comment] 2016-05-22 20:28
@JamiesWhiteShirt I'm guessing a temporary workaround in the meantime would be to set the worldgen frequency of Iocalfaeus Gas to 0 in config?

**Comment by JamiesWhiteShirt** [comment] 2016-05-22 20:30
If that is the actual problem, yes. @31trainman could you try that and see if it still happens?

**Comment by lawremi** [comment] 2016-05-22 20:33
Just looked at the GasTypeLightSensitive.java in Glenn's Gases and found that it will replace vanilla stone with warmStone, but otherwise it will modify the metadata of the existing block.

The line
```
int otherMetadata = otherBlock == Blocks.stone ? -1 : world.getBlockMetadata(x1, y1, z1);
```

Should probably be:
```
int otherMetadata = otherBlock == Gases.blocks.warmStone ? world.getBlockMetadata(x1, y1, z1) : -1;
```

**Comment by JamiesWhiteShirt** [comment] 2016-05-22 20:34
@lawremi Correct! I just noticed that just as you wrote this. This is very likely the cause of the issue.

**Comment by JamiesWhiteShirt** [comment] 2016-05-22 21:43
I have probably just resolved this issue. It would be great if @31trainman could update to Glenn's Gases 1.6.5, [just released on CurseForge](http://minecraft.curseforge.com/projects/glenns-gases/files/2302196), and verify that the problem is gone.

**Comment by recalcitrantQ** [comment] 2016-05-22 22:02
@JamiesWhiteShirt  I can confirm that crashing is no longer occurring, and that Iocalfaeus Gas is now nonreactive with PFAA stone types

**Comment by JamiesWhiteShirt** [comment] 2016-05-22 23:01
Don't you just love when your bugs show up and bother other moddes :sweat_smile:

**Comment by 31trainman** [comment] 2016-05-22 23:47
Its working @JamiesWhiteShirt and @lawremi except what does this mean for future compatibility of the 2 mods?

**Comment by Webzoner97** [comment] 2016-05-22 23:51
So can we get reika to fix this? We found the cause, and I dont know why he's trying to render fire here either.

**Comment by 31trainman** [comment] 2016-05-22 23:53
Not sure reika will fix this odd bug as he may be doing who knows what else.

**Comment by JamiesWhiteShirt** [comment] 2016-05-22 23:56
@31trainman It just means that there is no longer any incompatibility between the mods. The incompatibility was not supposed to be there in the first place, since it was all caused by a bug in Glenn's Gases that had a side effect causing this issue.

Reika is not involved in this. DragonAPI appears in the stacktrace merely because it's injecting itself into Minecraft's block rendering to intercept in rare cases. The issue was with Glenn's Gases all along, and this issue should be closed as it is confirmed there no longer is an issue.

**Comment by lawremi** [comment] 2016-05-23 00:01
Thanks @JamiesWhiteShirt for the quick fix, sorry @ReikaKalseki for the noise, time to close this one before it goes off the rails.

**Closed by lawremi** 2016-05-23 00:01 UTC

**Comment by ReikaKalseki** [comment] 2016-05-23 01:18
@JamiesWhiteShirt Now do you see why I react to these people?

@lawremi Please lock it before more idiots waste more time, and let them go eat dirt or something instead.

"In before" someone starts mouthing off on the FTB subreddit six days from now about how I refuse to fix this crash...

**Comment by ReikaKalseki** [comment] 2016-05-23 18:46
Note 2: This bug has been confirmed to be the cause of at least one of the other "metadata randomly changing to invalid values" reports on my end (referenced above), and I am attempting to confirm the others.

**Comment by 1skandar** [comment] 2016-05-23 23:10
No it does not, and I have not seen the issue agaih. Sorry.

**Comment by TomeWyrm** [comment] 2016-05-24 06:28
@flyingbanana I'm REALLY hoping that was sarcasm, because that level of hostility shouldn't be directed at any modder this baselessly. There are numerous examples of stack traces reporting uninvolved mods that I simply don't have the time to dig up and point out to you. Please quit spreading such malicious misinformation.

Oh, you're a troll that has a hate-on because of the, irrelevant to ANY pertinent subject, preferences and lifestyle of another person you will never meet. Right. Well consider the previous diatribe to be directed at anyone else that is considering this type of baseless accusation in the future: Don't. It just hurts your case.

@31trainman The issue can be reproduced without dragonAPI. That, quite logically makes it not the fault of DragonAPI in ANY WAY. The mod authors of this mod, and DraognAPI have informed you of why it was showing up in the error report, but you seem incapable of accepting this.

@Webzoner97 Can you not read? The bug is not Reika's to fix. It already HAS been fixed in fact, and had nothing to do with Reika. It was a simple mistake and @JamiesWhiteShirt has fixed the error.

Thank you @JamiesWhiteShirt and @lawremi for not falling victim to the drama machine that follows Reika around and tries to stir up trouble.

**Comment by Webzoner97** [comment] 2016-05-24 07:29
So do that means reika fixed it?

**Comment by TomeWyrm** [comment] 2016-05-24 07:35
No, it means a person who actually could fix the bug (because another mod was causing it), did. That would be JamiesWhiteShirt, who fixed Glenn's Gases. The actual cause of the error.

Glenn's Gases isn't Reika's mod, so he can't fix it. Any other questions? Anything I should clarify?

**Comment by ReikaKalseki** [comment] 2016-05-24 08:26
> So do that means reika fixed it?

How do you manage to post here without first asphyxiating yourself with your mouse cord? It has been said *more than ten times*, by *five different people*, that it is not my doing, and the only other people saying it is my doing are a guy who spends his free time insulting people for their private interests (and, if experience (ex: http://i.imgur.com/r842cm2.png http://i.imgur.com/BjwlF86.png ) is any indication, has significant insecurities with his own, similar interests) and a guy who seems incapable of understanding that mods need to be installed to do anything.
